<div class="">

  <div class="block-header">
      <h2>EMPRESAS</h2>
  </div>

  <?php if ($view_msgError){ ?>
      <script> swal('Erro', '<?php echo $view_msgError; ?>', 'error'); </script>
  <?php } ?>
  <?php if ($view_msgSuccess){ ?>    
      <script> swal('Sucesso', '<?php echo $view_msgSuccess; ?>', 'success'); </script>
  <?php } ?>


  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
            <h2>
                EMPRESAS <!--<button type="button" class="btn btn-lg btn-primary waves-effect" onclick="window.location.href = '/<?php echo ROOT; ?>empresa/inserir';">ADICIONAR NOVO</button>-->
            </h2>          
        </div>
        <div class="body">        
              <div class="table-responsive">
                  <table class="table table-bordered table-striped table-hover dataTable js-exportable display" id="dataTable-empresas">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>CNPJ</th>                            
                            <th>Negócios Ganhos</th>   
                            <!--<th></th>-->
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($view_queries as $query): ?>
                        <tr>    
                            <td><?php echo $query['nome']; ?></td>
                            <td><?php echo $query['cnpj']; ?></td>              
                            <td><?php echo (int)$query['negocios']; ?></td>
                            <!--<td>                              
                              <button class="btn btn-link waves-effect" title="Editar" onclick="window.location.href='/<?php echo ROOT; ?>empresa/editar/id/<?php echo $query['idempresa']; ?>';"><i class="material-icons">create</i></button>
                              <a class="remover btn btn-link waves-effect" title="Remover" href="/<?php echo ROOT; ?>empresa/remover/id/<?php echo $query['idempresa']; ?>"><i class="material-icons">delete</i></a>                              
                            </td>-->
                        </tr>
                    <?php endforeach; ?>                                        
                    </tbody>
                  </table>
              </div>                      

        </div>
      </div> 
    </div>
  </div> 
  

</div> <!-- container-fluid -->

<script>
	$(function(){
		$('.remover').click(function(event){
			if(!confirm('Deseja realmente remover o registro selecionado?')){
				event.preventDefault();
				return false;
			}

			return true;
		});

    $('#dataTable-empresas').DataTable({        
      order: [[ 0, "asc" ]], 
    });   
    
    
	});
</script>

