	<div id="page-wrapper">

		<div class="row">
            <div class="col-lg-12">            	
                <h5 class="">
                	<?php if ($view_msgError){ ?>
						<div class="alert alert-danger">
						  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  			  <strong>Erro!</strong> <?php echo $view_msgError; ?>
						</div>
					<?php } ?>
					<?php if ($view_msgSucess){ ?>
						<div class="alert alert-success">
						  <button type="button" class="close" data-dismiss="alert">&times;</button>
						  <strong>Sucesso!</strong> <?php echo $view_msgSucess; ?>
						</div>
					<?php } ?>
				</h5>
				<h1 class="page-header">
                	Usuário
                </h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

		<form class="form-horizontal" role="form" method="post" action="<?php echo $view_action; ?>">
		  <?php if ($view_usuarios[0]['empresa']){ ?> 
			  <div class="form-group">
			    <label for="inputLoja" class="col-sm-2 control-label">Empresa</label>
			    <div class="col-sm-10"><?php echo $view_usuarios[0]['empresa']; ?> 
			    </div>
			  </div>		  
			  <?php if ($view_usuarios[0]['usuario_pai']){ ?> 
			  <div class="form-group">
			    <label for="inputGerente" class="col-sm-2 control-label">Gerente</label>
			    <div class="col-sm-10"><?php echo $view_usuarios[0]['usuario_pai']; ?> 
			    </div>
			  </div>		  
			  <?php } ?>
		  <?php } ?>
		  <div class="form-group">
		    <label for="inputNome" class="col-sm-2 control-label">Nome</label>
		    <div class="col-sm-10">
		      <?php echo $view_usuarios[0]['nome']; ?>
		    </div>
		  </div>		  
		  <div class="form-group">
		    <label for="inputLogin" class="col-sm-2 control-label">Login</label>
		    <div class="col-sm-10">
		      <?php echo $view_usuarios[0]['login']; ?>
		    </div>
		  </div>		  
		  <div class="form-group">
		    <label for="inputAtivo" class="col-sm-2 control-label">Ativo</label>
		    <div class="col-sm-10">
		      <?php echo $view_usuarios[0]['ativo']; ?>
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputEmail" class="col-sm-2 control-label">Permissão</label>
		    <div class="col-sm-10"><?php echo $view_usuarios[0]['permissao']; ?> 
		    </div>
		  </div>		  
		  		  
		</form>
	</div>	
	