<div id="page-wrapper">

		<div class="row">
            <div class="col-lg-12">
                <h5 class="">
                    
                        <div class="alert alert-danger">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <strong>ATENÇÃO!</strong> Este módulo não está habilitado.
                        </div>
                    
                </h5>
                <h1 class="page-header">
                	Acesso Indisponível
                </h1>
            </div>
            <!-- /.col-lg-12 -->          
        </div>
        <!-- /.row -->

        