	<div class="block-header">
        <h2>DASHBOARD</h2>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="">
                
                <div class="body">

                	
				    
                	<div class="row clearfix">		

                		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		                	<a href="/<?php echo ROOT; ?>negocio" style="cursor:pointer;text-decoration:none;">
		                    <div class="info-box" style="cursor:pointer;">
		                        <div class="icon bg-cyan">
		                            <i class="material-icons">business_center</i>
		                        </div>
		                        <div class="content">
		                            <div class="text">NEGÓCIOS</div>
		                            <div class="number"><?php echo $view_total_negocios; ?></div>
		                        </div>
		                    </div>
		                	</a>
		                </div>                
		                
		                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		                	<a href="/<?php echo ROOT; ?>contato" style="cursor:pointer;text-decoration:none;">
		                    <div class="info-box" style="cursor:pointer;">
		                        <div class="icon bg-cyan">
		                            <i class="material-icons">group</i>
		                        </div>
		                        <div class="content">
		                            <div class="text">CONTATOS</div>
		                            <div class="number"><?php echo $view_total_contatos; ?></div>
		                        </div>
		                    </div>
		                	</a>
		                </div>		                		                

		                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		                	<a href="/<?php echo ROOT; ?>empresa" style="cursor:pointer;text-decoration:none;">
		                    <div class="info-box" style="cursor:pointer;">
		                        <div class="icon bg-cyan">
		                            <i class="material-icons">business</i>
		                        </div>
		                        <div class="content">
		                            <div class="text">EMPRESAS</div>		                            
		                            <div class="number"><?php echo $view_total_empresas; ?></div>
		                        </div>
		                    </div>
		                	</a>
		                </div>		                
		                
		            </div>
		        	
		            <div class="row clearfix">
				        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				            <div class="card">
				                <div class="body">
				                    <blockquote>Olá <?php echo $view_userInfo['nome']; ?>, bem-vindo ao Aplicativo <?php echo TITLE; ?>.</blockquote>
				                    <a class="btn btn-lg btn-primary" href="/<?php echo ROOT; ?>contato/inserir">
				                		CLIQUE AQUI PARA PREENCHER<br>O FORMULÁRIO DE CADASTRO
				                	</a>
				                </div>
				            </div>
				        </div>
				    </div>        

                    
                </div>
            </div>
        </div>
    </div>
    

    <?php //echo $view_template_agenda; ?>
    


            