<div id="page-wrapper">

		<div class="row">
            <div class="col-lg-12">
                <h5 class="">
                    
                        <div class="alert alert-info">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <strong>Informação!</strong> Esta página está em manutenção, em breve estará em funcionamento
                        </div>
                    
                </h5>
                <h1 class="page-header">
                	Em manutenção                	
                </h1>
            </div>
            <!-- /.col-lg-12 -->          
        </div>
        <!-- /.row -->

        